### ISSUE TITLE
Store application-specific data ("appDataFolder")

### ISSUE THREAD

**Issue by mrladeia** [ammarptn/GDrive-Rest-Android#12]
Hello!

I saw that Google will remove access to the appdata folder, but when I read it I thought they were downgrading the API version and it would be necessary to migrate to the REST API.

My interpretation was the same as this:
_"I guess you just need to use the new version of the Google Drive Android API https://developers.google.com/drive/api/v3/appdata"_

Ref: https://stackoverflow.com/questions/54094421/what-is-the-future-of-app-data-folder-in-google-drive

Since WhatsApp also uses this function to store backup files.

The v3 page in the documentation says nothing about deprecated
Ref: https://developers.google.com/drive/api/v3/appdata

Is there any more concrete news from google about this?

Thanks

**Comment by mrladeia** [comment]
There was that same question

https://github.com/gsuitedevs/android-samples/issues/117

**Comment by ammarptn** [comment]
The only place I can find about appdata deprecation is here :
https://developers.google.com/drive/android/deprecation

I understand why they want to remove it soon, From my perspective, store some application data on the Google Drive might not suit for every solution, you need user's consent and permission in order to access it. if your appdata consume too much space, they might delete your appdata from their drive.

This lead to heavy error handling on your application's code. (permission, file not found, no more space left, etc.)

The only advantage that i can think about for store file on google drive's appdata folder is developers no need to pay for the storage space.

Store it in other place(Firebase storage, AWS bucket , etc.) might give you better control over appdata.

**Comment by abharna** [comment]
upload file is not working

**Comment by ammarptn** [comment]
> upload file is not working

please create new issue and provide logcat
